

insert into pro_month_pyramid_day10(
`ym`,
  `commodity_style_no` ,
  `category_name1` ,
  `category_name2` ,
  `channel`,
  `sale_commodity_num_tm_year`,
  `sale_total_amount_tm_year`,
  `sale_commodity_num_tm_30d`,
  `sale_total_amount_tm_30d`,
  `sale_commodity_num_tm_7d`,
  `sale_total_amount_tm_7d`,
  `commodity_no`,
  `commodity_supplier_code`,
  `commodity_style`,
  `shoe_tree`,
  `product_season_name`,
  `product_year_name`,
  `default_pic`,
  `first_sale_date_tmall`,
  `inventory_quantity`,
  `nonarrival`,
  `rn`,
  `rank_7`,
  `rank_14`,
  `rank_21`,
  `rank_28`,
  `sale_trend_score` ,
  `offline_selling_rate`,
  `forcast_rank`,
  `forcast_level`,
  `forcast_qty`,
  `forcast_qty_rate`,
  `plan_level`,
  `set_level`,
  `pct_sale_sku_cat4_l12mth`,
  `rank_sale_l12mth`,
  `num_sale_l12mth`,
  `delta_rank_l12mth_sale`,
  `trend_pct_sale_l12_34wk`,
  `delta_rank_l12_34wk_sale`,
  `pct_sale_sku_cat4_l1mth`,
  `pct_sale_cat4_l1wk`,
  `rank_sale_l1wk`,
  `rank_p1mth_prevyr_l1wk`,
  `content`
)
select
`ym`,
  `commodity_style_no` ,
  `category_name1` ,
  `category_name2` ,
  `channel`,
  `sale_commodity_num_tm_year`,
  `sale_total_amount_tm_year`,
  `sale_commodity_num_tm_30d`,
  `sale_total_amount_tm_30d`,
  `sale_commodity_num_tm_7d`,
  `sale_total_amount_tm_7d`,
  `commodity_no`,
  `commodity_supplier_code`,
  `commodity_style`,
  `shoe_tree`,
  `product_season_name`,
  `product_year_name`,
  `default_pic`,
  `first_sale_date_tmall`,
  `inventory_quantity`,
  `nonarrival`,
  `rn`,
  `rank_7`,
  `rank_14`,
  `rank_21`,
  `rank_28`,
  `sale_trend_score` ,
  `offline_selling_rate`,
  `forcast_rank`,
  `forcast_level`,
  `forcast_qty`,
  `forcast_qty_rate`,
  `plan_level`,
  `set_level`,
  `pct_sale_sku_cat4_l12mth`,
  `rank_sale_l12mth`,
  `num_sale_l12mth`,
  `delta_rank_l12mth_sale`,
  `trend_pct_sale_l12_34wk`,
  `delta_rank_l12_34wk_sale`,
  `pct_sale_sku_cat4_l1mth`,
  `pct_sale_cat4_l1wk`,
  `rank_sale_l1wk`,
  `rank_p1mth_prevyr_l1wk`,
  `content`
 from pro_month_pyramid where ym = '2019-06'

